nginx:
  build: nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "9086:9086"
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: loanCalculator
    MYSQL_USER: user
    MYSQL_PASSWORD: password
cache:
  image: memcached
  ports:
    - "11311:11311"
php:
  build: lumen-ms
  container_name: lumen-php
  volumes:
    - ./lumen-ms:/app
  working_dir: /app/public
  command: chown -R :www-data /app
  command: chown www-data:www-data -R ../storage/
  command: chmod -R 777 /app
  command: chmod -R o+w /app/storage
  command: php-fpm
  links:
    - db
    - cache
  ports:
    - "9002:9002"
  environment:
    APP_ENV: local
    APP_DEBUG: "true"
    APP_KEY: 123
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db

    DB_DATABASE: loanCalculator
    DB_USERNAME: user
    DB_PASSWORD: password
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
node_client:
  build: react-app
  ports:
    - "8081:8000"
node_admin:
  build: react-admin
  ports:
    - "8082:8000"
