nginx:
  build: nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "9086:9086"
php:
  build: ./
  container_name: lumen-php
  volumes:
    - ./:/app
  working_dir: /app/public
  command: chown -R :www-data /app
  command: chown www-data:www-data -R ../storage/
  command: chmod -R 777 /app
  command: chmod -R o+w /app/storage
  command: php-fpm
  links:
    - db
    - cache
  ports:
    - "9002:9002"
  environment:
    APP_ENV: local
    APP_DEBUG: "true"
    APP_KEY: 123
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db

    DB_DATABASE: loanCalculator
    DB_USERNAME: root
    DB_PASSWORD: root
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
db:
  image: mysql
  ports:
    - "3308:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
cache:
  image: memcached
  ports:
    - "11311:11311"
